config/routes.rb
CRMEngsoft::Application.routes.draw do
  resources :marketing_actions

  resources :marketing_campaigns do
  	get 'delete', :on => :collection
  	
  	resources :marketing_actions do
  		get 'delete', :on => :collection
  	end
  end

  resources :support_case_events

  resources :clients

  resources :comments

  resources :subjects

  resources :faqs

  resources :contacts

  resources :contact_groups

  resources :newsletters

  resources :employees

  resources :support_cases

  resources :questions

  resources :calls

  resources :banners

  resources :reports

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/faq.rb
# encoding: UTF-8
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question, :subject_id, :subject
  belongs_to :subject

  validates :question,
    :presence => {:message => "Favor digitar uma pergunta"},
    :uniqueness => {:message => "Essa pergunta já existe no sistema"},
    :length => { :in => 5..255 , :message => "Tem que ter entre 5 e 255 caracteres"}
  validates :answer, :presence => {:message => "Favor digitar uma resposta"}
  validates :subject_id, :presence => {:message => "Favor digitar um assunto"}

  scope :sorted, order('faqs.subject_id ASC')
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_filter :find_subject
  before_filter :all_subjects
  
  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.sorted
    if @subject
      @faqs = @faqs.where(:subject_id => @subject.id)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs, include: 'subject' }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq, include: 'subject' }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new 
    @faq = Faq.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'FAQ criada com sucesso.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        @subjects = Subject.all
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        format.html { redirect_to @faq, notice: 'FAQ atualizada com sucesso.' }
        format.json { head :no_content }
      else
        @subjects = Subject.all
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @faq = Faq.find(params[:id])
  end

  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to faqs_url }
      format.json { head :no_content }
    end
  end

  private

  def find_subject
    if params[:subject_id]
      @subject = Subject.find_by_id(params[:subject_id])
    end
  end

  def all_subjects
    @subjects = Subject.all
  end
end

app/helpers/fa_qs_helper.rb
module FaQsHelper
end

app/views/faqs/_form.html.erb
<% readonly ||= false %>
<%= error_messages_for(@faq) %>

<div class="control-group">
	<%= f.label :subject_id, "Tópico", :class => "control-label strong" %>
	<div class="controls">
      <%= f.select :subject_id, @subjects.collect {|s| [s.subject, s.id]}, {}, :disabled => readonly %>&nbsp;
	  <%= link_to '', {:controller => 'subjects', :action => 'new'}, {:class => "icon-plus-sign", :target => '_new', :style => "font-size:20px"} %>
    </div>
</div>
<div class="control-group">
    <%= f.label :question, "Dúvida", :class => "control-label strong" %>
	<div class="controls">
      <%= f.text_field :question, :placeholder => "Dúvida", :readonly => readonly, :style => "width: 700px;" %>
    </div>
</div>
<div class="control-group">
	<%= f.label :answer, "Resposta", :class => "control-label strong" %>
	<div class="controls">
	  <%= f.text_area :answer, :placeholder => "Resposta", :readonly => readonly, :style => "height:200px; width: 700px;" %>
    </div>
</div>

app/views/faqs/delete.html.erb
<h2><%= @page_title = "Deletar FAQ" %></h2><hr />

<p class="red-text strong" style="font-size:16px">Você tem certeza que deseja deletar permanentemente essa FAQ?</p>
<%= form_for @faq, :html => {:class => "form-horizontal"} do |f| -%>

  <%= render(:partial => 'form', :locals => {:f => f, :readonly => true}) %>    
  <div class="control-group">
	  <div class="controls">
		  <%= button_to "Deletar FAQ", faq_path(@faq), :method => 'delete', :class => "btn btn-small dark-blue" %>
	  </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de FAQs', faqs_path, :class => "btn btn-small light-blue inverse" %>

app/views/faqs/edit.html.erb
<h2><%= @page_title = "Alterar FAQ" %></h2><hr />

<%= form_for @faq, :validate => true, :html => {:class => "form-horizontal"} do |f| %>
  
  <%= render(:partial => 'form', :locals => {:f => f}) %>    
  <div class="control-group">
    <div class="controls">
      <%= f.submit("Atualizar", :class => "btn btn-small dark-blue") %>
    </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de FAQs', faqs_path, :class => "btn btn-small light-blue inverse" %>

app/views/faqs/index.html.erb
<div class="box bordered" style="position:relative;">
	<div class="box-header" >
		<i class="icon-th-list"></i><%= link_to "Tópicos", subjects_path %> >> <%= @page_title = "Perguntas e Respostas" %>
	</div>

	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th style="min-width: 80px;">Ações</th>
				<th>Tópico</th>
			    <th>Pergunta</th>
				<th>Resposta</th>
			</tr>
		</thead>
		<tbody>
			<% @faqs.each do |faq| %>
			  <tr>
  			    <td class="td-actions">
  			        <%= link_to '', {:action => 'show', :id => faq.id}, :class => "icon-eye-open", :title => "Visualizar" %>&nbsp;
  					<%= link_to '', {:action => 'edit', :id => faq.id}, :class => "icon-edit", :title => "Editar" %>&nbsp;
  					<%= link_to '', {:action => 'delete', :id => faq.id}, :class => "icon-remove", :title => "Deletar" %>
  				</td>
			    <td><%= link_to faq.subject.subject, {:controller => 'subjects', :action => 'show', :id => faq.subject.id}, :title => faq.subject.description %></td>
				<td><%= faq.question %></td>
				<td><%= truncate(faq.answer, :length => 60) %></td>
			  </tr>
			<% end %>
		</tbody>
	</table>
</div>

<br />

<%= link_to 'Novo tópico', new_subject_path, :class => "btn btn-small light-blue inverse" %>&nbsp; &nbsp;&nbsp;
<%= link_to 'Nova dúvida', new_faq_path, :class => "btn btn-small light-blue inverse" %>&nbsp; |&nbsp;&nbsp;
<%= link_to 'Ir para a lista de tópicos', subjects_path, :class => "btn btn-small light-blue inverse" %>

app/views/faqs/new.html.erb
<h2><%= @page_title = "Nova Dúvida" %></h2><hr />

<%= form_for @faq, :validate => true, :html => {:class => "form-horizontal"} do |f| %>
  
  <%= render(:partial => 'form', :locals => {:f => f}) %>    
  <div class="control-group">
    <div class="controls">
      <%= f.submit("Criar Dúvida", :class => "btn btn-small dark-blue") %>
    </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de FAQs', faqs_path, :class => "btn btn-small light-blue inverse" %>

app/views/faqs/show.html.erb
<h2><%= @page_title = "Visualizar FAQ" %></h2><hr />

<% if notice %>
	<div class="alert green fade in">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= notice %>
	</div>
<% end %>

<%= form_for @faq, :html => {:class => "form-horizontal"} do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f, :readonly => true}) %> 
  <%= render(:partial => 'partials/timestamps', :locals => {:obj => @faq}) %>
  <div class="control-group">
    <div class="controls">
      <%= link_to 'Editar FAQ', {:action => 'edit', :id => @faq.id}, :class => "btn btn-small dark-blue" %>
  </div>
<% end %>

<br />
<%= link_to 'Ir para a lista de FAQs', faqs_path, :class => "btn btn-small light-blue inverse" %>&nbsp; &nbsp;&nbsp;
<%= link_to 'Nova pergunta', new_faq_path, :class => "btn btn-small light-blue inverse" %>