config/routes.rb
CRMEngsoft::Application.routes.draw do
  resources :marketing_actions

  resources :marketing_campaigns do
  	get 'delete', :on => :collection
  	
  	resources :marketing_actions do
  		get 'delete', :on => :collection
  	end
  end

  resources :support_case_events

  resources :clients

  resources :comments

  resources :subjects

  resources :faqs

  resources :contacts

  resources :contact_groups

  resources :newsletters

  resources :employees

  resources :support_cases

  resources :questions

  resources :calls

  resources :banners

  resources :reports

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :address, :name, :cpf, :remote_id
  has_many :support_cases
  has_many :comments
  has_many :support_case_events

  def isFree
    if(:support_cases==nil)
      return true
    else
      return false
    end
  end
end

app/controllers/employees_controller.rb
require 'prawn'

class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json=> @employees.to_json }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
      format.pdf do
        pdf = EmployeeReport.new(@employee,view_context)
        send_data pdf.render, filename:
            "employeeInvoice.pdf",
            type: "application/pdf"
      end
    end
  end


  def import
    @wsemployee = employees_web_service params[:id]
    @employee = Employee.where("remote_id = ?", params[:id])
    if(@employee!=nil)
      @employee_id = @employee.id
    else
      @employee_id = nil;
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wsemployee }
    end

  end

  def saveImport
    @wsemployee = WsEmployee.new(params[:wsemployee])
    @employee_id = params[:employee_id];

    if(@employee_id!=nil)
      @employee = Employee.find(@employee_id)
      @employee.update_attributes(params[:wsemployee])
    else
      @employee = Employee.new
      @employee.name = @wsemployee.name
      @employee.cpf = @wsemployee.cpf
      @employee.address = @wsemployee.address
      @employee.remote_id = @wsemployee._id
      @employee.save
    end
    redirect_to(@employee)

  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class="control-group">
  <%= f.label :name ,"Nome", :class => "control-label strong" %>
  <%= f.text_field :name%>
</div>

<div class="control-group">
  <%= f.label :cpf ,"Cpf", :class => "control-label strong"%>
  <%= f.text_field :cpf %>
</div>


<div class="control-group">
  <%= f.label :address,"Endereco", :class => "control-label strong" %>
  <%= f.text_field :address %>
</div>

app/views/employees/edit.html.erb
<h1>Edicao de funcionario:</h1>
<%= form_for @employee, :html => {:class => "form-horizontal"} do |f|%>
    <%= render(:partial => 'form',:locals => {:f => f}) %>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Salvar", :class => "btn btn-small dark-blue"%>
      </div>
    </div>
<%end%>

<%= link_to 'Voltar', support_cases_path ,:class => "btn btn-small dark-blue" %>

app/views/employees/import.html.erb
<h1>Importar Funcionarios de Base remota</h1>

<%= form_for @wsemployee,:action => 'saveImport',:employee_id=>@employee_id, :html => {:class => "form-horizontal"} do |f|%>
    <%= render(:partial => 'form',:locals => {:f => f}) %>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Importar", :class => "btn btn-small dark-blue"%>
      </div>
    </div>
<%end%>

<%= link_to 'Voltar', support_cases_path %>

app/views/employees/index.html.erb
<div class="box bordered" style="position:relative;">
  <div class="box-header" >
    <i class="icon-th-list"></i><%= @page_title = "Lista de Funcionarios (Remoto)" %>
  </div>

  <table class="table table-striped data-table">
    <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>CPF</th>
    </tr>
    </thead>

    <tbody>
    <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.address%></td>
          <td><%= employee.cpf%></td>
          <td class="td-actions">
            <%= link_to 'Visualizar', employee ,:class => "btn btn-small dark-blue"%>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br />

app/views/employees/new.html.erb
<h1>Novo Funcionario:</h1>

<%= form_for @employee, :html => {:class => "form-horizontal"} do |f|%>
    <%= render(:partial => 'form',:locals => {:f => f}) %>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Salvar", :class => "btn btn-small dark-blue"%>
      </div>
    </div>
<%end%>

<%= link_to 'Voltar', support_cases_path ,:class => "btn btn-small dark-blue" %>

app/views/employees/show.html.erb
<div id="employee_values" class="box bordered" style="position:relative;">
  <h4>Dodos do Funcionario:</h4>
  <p>
    <b>Nome:</b>
    <%= @employee.name%>
  </p>

  <p>
    <b>Endereco</b>
    <%= @employee.address%>
  </p>

  <p>
    <b>CPF:</b>
    <%= @employee.cpf%>
  </p>

<%= link_to 'Back', employees_path, :class => "btn btn-small dark-blue"%>