config/routes.rb
CRMEngsoft::Application.routes.draw do
  resources :marketing_actions

  resources :marketing_campaigns do
  	get 'delete', :on => :collection
  	
  	resources :marketing_actions do
  		get 'delete', :on => :collection
  	end
  end

  resources :support_case_events

  resources :clients

  resources :comments

  resources :subjects

  resources :faqs

  resources :contacts

  resources :contact_groups

  resources :newsletters

  resources :employees

  resources :support_cases

  resources :questions

  resources :calls

  resources :banners

  resources :reports

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  attr_accessible :height, :name, :size_type, :width, :image
  has_attached_file :image
  
  has_many :marketing_actions

  def banner_types
  	return {'Cabecalho' => [728, 90], 
                 'Banner' => [468, 60], 
                 'Botao' => [125, 125],
                 'Meio-banner' => [234, 60],
                 'Arranha-ceu' => [120, 600],
                 'Arranha-ceu largo' => [160, 600],
                 'Banner vertical' => [120, 240]}
  end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banners }
    end
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
    @banner = Banner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/new
  # GET /banners/new.json
  def new
    @banner = Banner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/1/edit
  def edit
    @banner = Banner.find(params[:id])
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(params[:banner])
    size = @banner.banner_types[@banner.size_type]
    @banner.width = size.first
    @banner.height = size.last

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'O Banner foi criado com sucesso.' }
        format.json { render json: @banner, status: :created, location: @banner }
      else
        format.html { render action: "new" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banners/1
  # PUT /banners/1.json
  def update
    @banner = Banner.find(params[:id])
    size = @banner.banner_types[@banner.size_type]
    @banner.width = size.first
    @banner.height = size.last

    respond_to do |format|
      if @banner.update_attributes(params[:banner])
        format.html { redirect_to @banner, notice: 'O Banner foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @banner = Banner.find(params[:id])
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to banners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<% readonly ||= false %>
<%= error_messages_for(@call) %>
<div class="control-group">
    <%= f.label :name, "Nome", :class => "control-label strong" %>
  <div class="controls">
      <%= f.text_field :name, :placeholder => "Nome", :readonly => readonly %>
    </div>
</div>
<div class="control-group">
  <%= f.label :size, "Tamanho", :class => "control-label strong" %>
  <div class="controls">
    <select name="banner[size_type]">
      <% @banner.banner_types.each_key do |type| %>
        <option value="<%= type %>"><%= type %>(<%= @banner.banner_types[type].first %>x<%= @banner.banner_types[type].last %>)</option>
      <% end %>
    </select>
    </div>
</div>
<div class="control-group">
  <%= f.label :image, "Imagem", :class => "control-label strong" %>
  <div class="controls">
    <% if !readonly %>
      <%= f.file_field :image, :readonly => readonly%>
    <% else %>
      <%= image_tag @banner.image.url %>
    <% end %>
  </div>

</div>

app/views/banners/delete.html.erb
<h2><%= @page_title = "Excluir banner" %></h2><hr />

<p class="red-text strong" style="font-size:16px">Você tem certeza que deseja deletar permanentemente esse banner?</p>
<%= form_for @banner, :html => {:class => "form-horizontal"} do |f| -%>

  <%= render(:partial => 'form', :locals => {:f => f, :readonly => true}) %>    
  <div class="control-group">
	  <div class="controls">
		  <%= button_to "Excluir banner", banner_path(@banner), :method => 'delete', :class => "btn btn-small dark-blue" %>
	  </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de banners', banners_path, :class => "btn btn-small light-blue inverse" %>

app/views/banners/edit.html.erb
<h2><%= @page_title = "Alterar Banner" %></h2><hr />
<%= form_for @banner, :validate => true, :html => {:class => "form-horizontal", :multipart => true} do |f| %>
  
  <%= render(:partial => 'form', :locals => {:f => f}) %>    
  <div class="control-group">
    <div class="controls">
      <%= f.submit("Atualizar", :class => "btn btn-small dark-blue") %>
    </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de Banners', banners_path, :class => "btn btn-small light-blue inverse" %>

app/views/banners/index.html.erb
<div class="box bordered" style="position:relative;">
  <div class="box-header" >
    <%= @page_title = "Banners" %>
  </div>

  <table class="table table-striped data-table">
    <thead>
      <tr>
        <th>Ações</th>
        <th>Nome</th>
          <th>Tamanho</th>
          <th>Tipo</th>
      </tr>
    </thead>
    <tbody>
      <% @banners.each do |banner| %>
        <tr>
            <td class="td-actions">
            <%= link_to '', {:action => 'show', :id => banner.id}, :class => "icon-eye-open", :title => "Visualizar" %>&nbsp;
            <%= link_to '', {:action => 'edit', :id => banner.id}, :class => "icon-edit", :title => "Editar" %>&nbsp;
            <%= link_to '', {:action => 'delete', :id => banner.id}, :class => "icon-remove", :title => "Deletar" %>
          </td>
          <td><%= banner.name %></td>
          <td>(<%= banner.width %>x<%= banner.height %>)</td>
          <td><%= banner.size_type %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br />

<%= link_to 'Novo Banner', new_banner_path, :class => "btn btn-small light-blue inverse" %>&nbsp; &nbsp;&nbsp;

app/views/banners/new.html.erb
<h2><%= @page_title = "Novo Banner" %></h2><hr />

<%= form_for @banner, :validate => true, :html => {:class => "form-horizontal", :multipart => true} do |f| %>
  
  <%= render(:partial => 'form', :locals => {:f => f}) %>    
  <div class="control-group">
    <div class="controls">
      <%= f.submit("Criar", :class => "btn btn-small dark-blue") %>
    </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de Banners', banners_path, :class => "btn btn-small light-blue inverse" %>

app/views/banners/show.html.erb
<h2><%= @page_title = "Visualizar Banner" %></h2><hr />

<% if notice %>
  <div class="alert green fade in">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %>

<%= form_for @banner, :html => {:class => "form-horizontal", :multipart => true} do |f| -%>

  <%= render(:partial => 'form', :locals => {:f => f, :readonly => true}) %>    
  <div class="control-group">
    <div class="controls">
      <%= link_to 'Editar Banner', {:action => 'edit', :id => @banner.id}, :class => "btn btn-small dark-blue" %>
  </div>
<% end %>

<br />
<%= link_to 'Ir para a lista de banners', banners_path, :class => "btn btn-small light-blue inverse" %>&nbsp; &nbsp;&nbsp;
<%= link_to 'Novo Banner', new_banner_path, :class => "btn btn-small light-blue inverse" %>