config/routes.rb
CRMEngsoft::Application.routes.draw do
  resources :marketing_actions

  resources :marketing_campaigns do
  	get 'delete', :on => :collection
  	
  	resources :marketing_actions do
  		get 'delete', :on => :collection
  	end
  end

  resources :support_case_events

  resources :clients

  resources :comments

  resources :subjects

  resources :faqs

  resources :contacts

  resources :contact_groups

  resources :newsletters

  resources :employees

  resources :support_cases

  resources :questions

  resources :calls

  resources :banners

  resources :reports

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/marketing_campaign.rb
class MarketingCampaign < ActiveRecord::Base
	attr_accessible :begin_date, :description, :end_date, :estimated_begin_date, :estimated_end_date, :estimated_revenue, :name, :status, :revenue, :financial_feedback
  
  has_many :marketing_actions, :dependent => :destroy
  
  has_and_belongs_to_many :contact_groups
  
  def value
  	sum = 0
  	
  	if(!marketing_actions.empty?)
  		for marketing_action in marketing_actions
  			sum += marketing_action.value
  		end
  	end
  
  	return sum
  end
  
  def next_status
  	self.status = MarketingCampaign.next_marketing_status[self.status]
  end
  
  def previous_status
  	self.status = MarketingCampaign.previous_marketing_status[self.status]
  end
  
  def cancel_status
  	self.status = 8
  end
  
  def self.marketing_status
  	return {0 => 'Criada',
  					1 => 'Aberta',
  					2 => 'Em espera',
  					3 => 'Aprovada',
  					4 => 'Desaprovada',
  					5 => 'Iniciada',
  					6 => 'Finalizada',
  					7 => 'A ser corrigida',
  					8 => 'Cancelada',
  					9 => 'Desaprovada'}
  end
  
  def self.next_marketing_status
  	return {0 => 1,
  					1 => 2,
  					2 => 3,
  					3 => 5,
  					4 => 9,
  					5 => 6,
  					6 => 6,
  					7 => 2,
  					8 => 8,
  					9 => 7}
  end
  
  def self.previous_marketing_status
  	return {0 => 0,
  					1 => 0,
  					2 => 4,
  					3 => 2,
  					4 => 2,
  					5 => 3,
  					6 => 5,
  					7 => 2,
  					8 => 1,
  					9 => 2}
  end
end

app/controllers/marketing_campaigns_controller.rb
class MarketingCampaignsController < ApplicationController
	before_filter :get_role_session	
	
  # GET /marketing_campaigns
  # GET /marketing_campaigns.json
  def index
  	# Dependendo do perfil do candidato, selecionar todas as  campanhas ou somente as passadas do estado "Em espera"
  	if(@role == "FIN")
  		@marketing_campaigns = MarketingCampaign.where("status > 1 and status != 8")
  	else
  		@marketing_campaigns = MarketingCampaign.all
  	end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @marketing_campaigns }
    end
  end

  # GET /marketing_campaigns/1
  # GET /marketing_campaigns/1.json
  def show
    @marketing_campaign = MarketingCampaign.find(params[:id])
    
    @contact_groups = @marketing_campaign.contact_groups
    
    @status = @marketing_campaign.status

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @marketing_campaign.to_json({:methods => :value}) }
    end
  end

  # GET /marketing_campaigns/new
  # GET /marketing_campaigns/new.json
  def new
    @marketing_campaign = MarketingCampaign.new
    @marketing_campaign.status = 0
    
    @contact_groups = ContactGroup.all
    
    @status = @marketing_campaign.status

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @marketing_campaign }
    end
  end

  # GET /marketing_campaigns/1/edit
  def edit
    @marketing_campaign = MarketingCampaign.find(params[:id])
    
    @contact_groups = ContactGroup.all
    
    if(params[:nextStatus])
    	@marketing_campaign.next_status
    elsif(params[:previousStatus])
    	@marketing_campaign.previous_status
    elsif(params[:cancelStatus])
    	@marketing_campaign.cancel_status
    end
    
    @status = @marketing_campaign.status
    
    if(@status == 5)
    	@marketing_campaign.begin_date = Date.today
    end
    
    if(@status == 6)
    	@marketing_campaign.end_date = Date.today
    end
  end

  # POST /marketing_campaigns
  # POST /marketing_campaigns.json
  def create
    @marketing_campaign = MarketingCampaign.new(params[:marketing_campaign])
    
    @marketing_campaign.contact_groups = Array.new
    
    if(params[:contact_groups] != nil)
		  params[:contact_groups].each do |id|
		  	@marketing_campaign.contact_groups << ContactGroup.find(id[0])
			end
		end
		
		@marketing_campaign.next_status

    respond_to do |format|
      if @marketing_campaign.save
        format.html { redirect_to @marketing_campaign, notice: 'Marketing campaign was successfully created.' }
        format.json { render json: @marketing_campaign, status: :created, location: @marketing_campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @marketing_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /marketing_campaigns/1
  # PUT /marketing_campaigns/1.json
  def update
    @marketing_campaign = MarketingCampaign.find(params[:id])
    
    if(params[:contact_groups] != nil)
    	@marketing_campaign.contact_groups = Array.new
    	
		  params[:contact_groups].each do |id|
		  	@marketing_campaign.contact_groups << ContactGroup.find(id[0])
			end
		end

    respond_to do |format|
      if @marketing_campaign.update_attributes(params[:marketing_campaign])
      	if(@marketing_campaign.status == 4)
					@marketing_campaign.next_status
					@marketing_campaign.save
				end
        format.html { redirect_to @marketing_campaign, notice: 'Marketing campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @marketing_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marketing_campaigns/1
  # DELETE /marketing_campaigns/1.json
  def destroy
    @marketing_campaign = MarketingCampaign.find(params[:id])
    @marketing_campaign.destroy

    respond_to do |format|
      format.html { redirect_to marketing_campaigns_url }
      format.json { head :no_content }
    end
  end
  
  def delete
    @marketing_campaign = MarketingCampaign.find(params[:id])
    
    @contact_groups = @marketing_campaign.contact_groups
    
    @status = @marketing_campaign.status
  end
  
  def get_role_session
  	@role = cookies[:access_level]
  end
end

app/helpers/marketing_campaigns_helper.rb
module MarketingCampaignsHelper
	def get_marketing_manager()
		return "CMRGM"
	end
	
	def get_financial_supervisor()
		return "FIN"
	end	
	
	def setReadonlyName(status)
		case status
			when 0
				return false
			when 1
				return false
			when 2
				return true
			when 3
				return true
			when 4
				return true
			when 5
				return true
			when 6
				return true
			when 7
				return false
			when 8
				return true
			when 9
				return true
			else
				return true
			end
	end
	
	def setReadonlyDescription(status)
		case status
			when 0
				return false
			when 1
				return false
			when 2
				return true
			when 3
				return true
			when 4
				return true
			when 5
				return true
			when 6
				return true
			when 7
				return false
			when 8
				return true
			when 9
				return true
			else
				return true
			end
	end
	
	def setReadonlyEstimatedBeginDate(status)
		case status
			when 0
				return true
			when 1
				return false
			when 2
				return true
			when 3
				return true
			when 4
				return true
			when 5
				return true
			when 6
				return true
			when 7
				return false
			when 8
				return true
			when 9
				return true
			else
				return true
			end
	end
	
	def setReadonlyEstimatedEndDate(status)
		case status
			when 0
				return true
			when 1
				return false
			when 2
				return true
			when 3
				return true
			when 4
				return true
			when 5
				return true
			when 6
				return true
			when 7
				return false
			when 8
				return true
			when 9
				return true
			else
				return true
			end
	end
	
	def setReadonlyEstimatedRevenue(status)
		case status
			when 0
				return true
			when 1
				return false
			when 2
				return true
			when 3
				return true
			when 4
				return true
			when 5
				return true
			when 6
				return true
			when 7
				return false
			when 8
				return true
			when 9
				return true
			else
				return true
			end
	end
	
	def setReadonlyRevenue(status)
		case status
			when 0
				return true
			when 1
				return true
			when 2
				return true
			when 3
				return true
			when 4
				return true
			when 5
				return true
			when 6
				return false
			when 7
				return true
			when 8
				return true
			when 9
				return true
			else
				return true
			end
	end
	
	def setReadonlyContactGroups(status)
		case status
			when 0
				return true
			when 1
				return false
			when 2
				return true
			when 3
				return true
			when 4
				return true
			when 5
				return true
			when 6
				return true
			when 7
				return false
			when 8
				return true
			when 9
				return true
			else
				return true
			end
	end
	
	def setReadonlyCommentary(status)
		case status
			when 0
				return true
			when 1
				return true
			when 2
				return false
			when 3
				return false
			when 4
				return false
			when 5
				return true
			when 6
				return true
			when 7
				return true
			when 8
				return true
			when 9
				return true
			else
				return true
			end
	end
end

app/views/marketing_campaigns/_form.html.erb
<% readonly ||= false %>
<%= error_messages_for(@marketing_campaign) %>

<%
		readonlyName = setReadonlyName(@status)
		readonlyDescription = setReadonlyDescription(@status)
		readonlyEstimatedBeginDate = setReadonlyEstimatedBeginDate(@status)
		readonlyEstimatedEndDate = setReadonlyEstimatedEndDate(@status)
		readonlyEstimatedRevenue = setReadonlyEstimatedRevenue(@status)
		readonlyRevenue = setReadonlyRevenue(@status)
		readonlyContactGroups = setReadonlyContactGroups(@status)
		readonlyCommentary = setReadonlyCommentary(@status)
%>

<div class="control-group">
    <%= f.label :name, "Nome", :class => "control-label strong" %>
	<div class="controls">
      <%= f.text_field :name, :placeholder => "Nome", :readonly => (readonly || readonlyName) %>
    </div>
</div>

<div class="control-group">
    <%= f.label :description, "Descrição", :class => "control-label strong" %>
	<div class="controls">
      <%= f.text_area :description, :placeholder => "Descrição", :readonly => (readonly || readonlyDescription) %>
    </div>
</div>

<div class="control-group">
    <%= f.label :status, "Estado", :class => "control-label strong" %>
	<div class="controls">
      <%= text_field_tag "status_text", MarketingCampaign.marketing_status[@marketing_campaign.status], :disabled => true %>
      <%= f.hidden_field :status %>
    </div>
</div>

<% if(@status != 0) %>
	<div class="control-group">
		  <%= f.label :value, "Preço", :class => "control-label strong" %>
		<div class="controls">
			<input id="marketing_campaign_value" type="text" value=<%= @marketing_campaign.value() %> size=30 readonly="true" placeholder="Preço" />
		  </div>
	</div>

	<div class="control-group">
		  <%= f.label :estimated_begin_date, "Data estimada de início da campanha", :class => "control-label strong" %>
		<div class="controls">
		    <%= f.date_select :estimated_begin_date, :placeholder => "Data estimada de início da campanha", :disabled => (readonly || readonlyEstimatedBeginDate) %>
		</div>
	</div>

	<div class="control-group">
		  <%= f.label :estimated_end_date, "Data estimada de fim da campanha", :class => "control-label strong" %>
		<div class="controls">
		    <%= f.date_select :estimated_end_date, :placeholder => "Data estimada de fim da campanha", :disabled => (readonly || readonlyEstimatedEndDate) %>
		</div>
	</div>

	<div class="control-group">
		  <%= f.label :estimated_revenue, "Retorno estimado", :class => "control-label strong" %>
		<div class="controls">
		    <%= f.text_field :estimated_revenue, :placeholder => "Retorno estimado", :readonly => (readonly || readonlyEstimatedRevenue) %>
		  </div>
	</div>
	
	<% if(@status == 5 || @status == 6) %>
		<div class="control-group">
				<%= f.label :begin_date, "Data de início da campanha", :class => "control-label strong" %>
			<div class="controls">
				 <%= f.text_field :begin_date, :placeholder => "Data de início da campanha", :readonly => true %>
			</div>
		</div>
		
		<% if(@status == 6) %>
			<div class="control-group">
					<%= f.label :end_date, "Data de fim da campanha", :class => "control-label strong" %>
				<div class="controls">
					 <%= f.text_field :end_date, :placeholder => "Data de fim da campanha", :readonly => true %>
					</div>
			</div>
		<% end %>
	<% end %>
	
	<% if(@status == 6) %>
		<div class="control-group">
				<%= f.label :revenue, "Retorno", :class => "control-label strong" %>
			<div class="controls">
				  <%= f.text_field :revenue, :placeholder => "Retorno", :readonly => (readonly || readonlyRevenue) %>
				</div>
		</div>
	<% end %>

	<% if(@marketing_campaign.marketing_actions) %>
		<div class="box bordered" style="position:relative;">
			<div class="box-header" >
				<i class="icon-th-list"></i>Ações de marketing
			</div>

			<table class="table table-striped data-table">
				<thead>
				<tr>
					<th>Nome</th>
					<th>Tipo</th>
					<th>Valor</th>
				</tr>
				</thead>

				<tbody>
			<% @marketing_campaign.marketing_actions.each do |marketing_action| %>
				<tr>
					<td><%= marketing_action.name %></td>
					<td><%= marketing_action.action_type %></td>
					<td><%= number_to_currency(marketing_action.value, :unit => 'R$', :separator => ',') %></td>
				</tr>
			<% end %>
			</table>
		</div>

	<% if(@marketing_campaign.id?) %>
		<%= link_to 'Vizualizar ações de marketing', marketing_campaign_marketing_actions_path(@marketing_campaign.id), {:class => "btn btn-small dark-blue"} %>
	<% end %>
	
	<% end %>

	<div class="box bordered" style="position:relative;">
		<div class="box-header" >
			<i class="icon-th-list"></i>Alvos - Grupos de Contatos&nbsp;&nbsp;&nbsp;&nbsp;
			<%= link_to '', {:controller => 'contact_groups', :action => 'new'}, {:class => "icon-plus-sign", :target => '_new', :style => "font-size:20px"} %>
		</div>
	
		<table class="table table-striped data-table">
			<thead>
				<tr>
					<th>Presente</th>
					<th>Nome do Grupo</th>
				</tr>
			</thead>
		
			<% for contact_group in @contact_groups %>
			<tr>
				<td>
					<% if(@marketing_campaign.contact_groups.include? contact_group) %>
						<%= check_box_tag("contact_groups[" + contact_group.id.to_s + "]", 1, true, {:disabled => (readonly || readonlyContactGroups), :class => "checkbox"}) %>
					<% else %>
						<%= check_box_tag("contact_groups[" + contact_group.id.to_s + "]", 1, false, {:disabled => (readonly || readonlyContactGroups), :class => "checkbox"}) %>
					<% end %>
				</td>
				<td><%= contact_group.name %></td>
			</tr>
			<% end %>
		</table>
	</div>
	
	<% if(@status >= 2) %>
		<div class="control-group">
			<%= f.label :financial_feedback, "Comentários", :class => "control-label strong" %>
			<div class="controls">
				<%= f.text_area :financial_feedback, :placeholder => "Comentários", :readonly => (readonly || readonlyCommentary) %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/marketing_campaigns/delete.html.erb
<h2><%= @page_title = "Deletar Campanha de Marketing" %></h2><hr />

<p class="red-text strong" style="font-size:16px">Você tem certeza que deseja deletar permanentemente essa campanha?</p>
<%= form_for @marketing_campaign, :html => {:class => "form-horizontal"} do |f| -%>

  <%= render(:partial => 'form', :locals => {:f => f, :readonly => true}) %>    
  <div class="control-group">
	  <div class="controls">
		  <%= button_to "Deletar Campanha de Marketing", marketing_campaign_path(@marketing_campaign), :method => 'delete', :class => "btn btn-small dark-blue" %>
	  </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de campanhas de marketing', marketing_campaigns_path, :class => "btn btn-small light-blue inverse" %>

app/views/marketing_campaigns/edit.html.erb
<h2><%= @page_title = "Alterar Campanha de Marketing" %></h2><hr />

<%= form_for @marketing_campaign, :validate => true, :html => {:class => "form-horizontal"} do |f| %>
  
  <%= render(:partial => 'form', :locals => {:f => f}) %>    
  <div class="control-group">
    <div class="controls">
      <%= f.submit("Atualizar", :class => "btn btn-small dark-blue") %>
    </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de campanhas de marketing', marketing_campaigns_path, :class => "btn btn-small light-blue inverse" %>

app/views/marketing_campaigns/index.html.erb
<div id="marketing_campaign_list" class="box bordered" style="position:relative;">
	<div class="box-header" >
		<i class="icon-th-list"></i><%= @page_title = "Campanhas de Marketing" %>
	</div>
	
	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th>Ações</th>
				<th>Name</th>
				<th>Estado</th>
			</tr>
		</thead>

	<% @marketing_campaigns.each do |marketing_campaign| %>
		<tr>
			<td class="td-actions">
				<%= link_to '', {:action => 'show', :id => marketing_campaign.id}, :class => "icon-eye-open", :title => "Visualizar" %>
				<% if((@role == get_marketing_manager && marketing_campaign.status != 2) || (@role == get_financial_supervisor && marketing_campaign.status == 2)) %>
					<% if(marketing_campaign.status != 5 && marketing_campaign.status != 6 && marketing_campaign.status != 8 && marketing_campaign.status != 9) %>
						<%= link_to '', {:action => 'edit', :id => marketing_campaign.id}, :class => "icon-edit", :title => "Editar" %>
					<% end %>
					<% if(marketing_campaign.status == 8) %>
						<%= link_to '', {:action => 'delete', :id => marketing_campaign.id}, :class => "icon-remove", :title => "Deletar"  %>
					<% end %>
				<% end %>
		  </td>
		  <td><%= marketing_campaign.name %></td>
		  <td><%= MarketingCampaign.marketing_status[marketing_campaign.status] %></td>
		</tr>
	<% end %>
	</table>
</div>
<br />

<%= link_to 'Nova campanha de marketing', new_marketing_campaign_path, :class => "btn btn-small light-blue inverse" %>

app/views/marketing_campaigns/new.html.erb
<h2><%= @page_title = "Nova Campanha de Marketing" %></h2><hr />

<%= form_for @marketing_campaign, :validate => true, :html => {:class => "form-horizontal"} do |f| %>
  
  <%= render(:partial => 'form', :locals => {:f => f}) %>    
  <div class="control-group">
    <div class="controls">
      <%= f.submit("Criar", :class => "btn btn-small dark-blue") %>
    </div>
  </div>
<% end %>

<%= link_to 'Ir para a lista de campanhas de marketing', marketing_campaigns_path, :class => "btn btn-small light-blue inverse" %>

app/views/marketing_campaigns/show.html.erb
<h2><%= @page_title = "Visualizar Campanha de Marketing" %></h2><hr />

<% if notice %>
	<div class="alert green fade in">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= notice %>
	</div>
<% end %>

<%= form_for @marketing_campaign, :html => {:class => "form-horizontal"} do |f| -%>

  <%= render(:partial => 'form', :locals => {:f => f, :readonly => true}) %>    
  <div class="control-group">
    <div class="controls">
    	<% if(@status != 5 && @status != 6 && @status != 8 && @status != 9) %>
    		<% if((@status == 2 && @role == get_financial_supervisor) || (@status != 2 && @role == get_marketing_manager)) %>
      		<%= link_to 'Editar Campanha de Marketing', {:action => 'edit', :id => @marketing_campaign.id}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      	<% end %>
      <% end %>
      <% if(@status == 1 || @status == 7 && @role != get_financial_supervisor) %>
      	<%= link_to 'Pedir Aprovação', {:action => 'edit', :id => @marketing_campaign.id, :nextStatus => true}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      <% elsif(@status == 2 && @role == get_financial_supervisor) %>
      	<%= link_to 'Aprovar', {:action => 'edit', :id => @marketing_campaign.id, :nextStatus => true}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      	<%= link_to 'Desaprovar', {:action => 'edit', :id => @marketing_campaign.id, :previousStatus => true}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      <% elsif(@status == 3 && @role != get_financial_supervisor) %>
      	<%= link_to 'Iniciar campanha', {:action => 'edit', :id => @marketing_campaign.id, :nextStatus => true}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      <% elsif(@status == 5 && @role != get_financial_supervisor) %>
      	<%= link_to 'Terminar campanha', {:action => 'edit', :id => @marketing_campaign.id, :nextStatus => true}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      <% elsif(@status == 8 && @role != get_financial_supervisor) %>
      	<%= link_to 'Reabrir campanha', {:action => 'edit', :id => @marketing_campaign.id, :previousStatus => true}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      <% end %>
      <% if(@status == 9 && @role != get_financial_supervisor) %>
      	<%= link_to 'Corrigir', {:action => 'edit', :id => @marketing_campaign.id, :nextStatus => true}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      <% end %>
      <% if(@status != 5 && @status != 6 && @status != 8 && @role != get_financial_supervisor) %>
      	</br>
      	<%= link_to 'Cancelar Campanha', {:action => 'edit', :id => @marketing_campaign.id, :cancelStatus => true}, :class => "btn btn-small dark-blue" %>&nbsp; &nbsp;&nbsp;
      <% end %>
  </div>
<% end %>

<br />
<%= link_to 'Ir para a lista de campanhas de marketing', marketing_campaigns_path, :class => "btn btn-small light-blue inverse" %>&nbsp; &nbsp;&nbsp;

<% if(@role != get_financial_supervisor) %>
	<%= link_to 'Nova Campanha de Marketing', new_marketing_campaign_path, :class => "btn btn-small light-blue inverse" %>
<% end %>